// src/integrations/supabase/client.ts

import { createClient } from '@supabase/supabase-js';
// supabase types generated by CLI may be empty in some environments (when
// the CLI couldn't reach the remote DB). Use a permissive any here so that
// Postgrest queries don't become uncallable (relation: never). This keeps
// type-safety locally where the generated types exist, but avoids breaking
// the dev environment when types are absent.
// Note: we intentionally don't use the generated `Database` type here because
// in some environments the generated types are empty which results in
// Postgrest methods becoming uncallable (relation: never). We prefer a
// permissive `any` at the client instantiation and keep `supabase/types.ts`
// available for places that import it directly.

const supabaseUrl = "https://apqrjkobktjcyrxhqwtm.supabase.co";
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcXJqa29ia3RqY3lyeGhxd3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTI4NzUsImV4cCI6MjA2Njk2ODg3NX0.99HhMrWfMStRH1p607RjOt6ChklI0iBjg8AGk_QUSbw";

const isTestEnvironment = process.env.NODE_ENV === 'test';

const storage = isTestEnvironment
  ? {
      getItem: async (_key: string) => null,
      setItem: async (_key: string, _value: string) => {},
      removeItem: async (_key: string) => {},
      clear: async () => {},
    }
  : localStorage;

// If the generated `Database` has no tables the generic will make `.from`
// accept `never`. To be resilient we cast to `any` at the call-site so
// queries remain usable in the editor and during dev. This is safe because
// runtime behaviour is unchanged; it only relaxes compile-time checks.
export const supabase = createClient<any>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  }
});